blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/YOUR_USERNAME/YOUR_REPO/discussions
    about: For general questions or setup help, please start a discussion instead.
